# A TOML linter such as Tombi can use this schema to validate your config.
# If you encounter any problems, please file an issue at https://github.com/yazi-rs/schemas.

#:schema https://yazi-rs.github.io/schemas/theme.json
